package mvp.wyyne.douban.moviedouban.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import mvp.wyyne.douban.moviedouban.api.model.SearchModelBean;

import mvp.wyyne.douban.moviedouban.model.SearchModelBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchModelBeanDaoConfig;

    private final SearchModelBeanDao searchModelBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchModelBeanDaoConfig = daoConfigMap.get(SearchModelBeanDao.class).clone();
        searchModelBeanDaoConfig.initIdentityScope(type);

        searchModelBeanDao = new SearchModelBeanDao(searchModelBeanDaoConfig, this);

        registerDao(SearchModelBean.class, searchModelBeanDao);
    }
    
    public void clear() {
        searchModelBeanDaoConfig.clearIdentityScope();
    }

    public SearchModelBeanDao getSearchModelBeanDao() {
        return searchModelBeanDao;
    }

}
