package mvp.wyyne.douban.moviedouban.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import mvp.wyyne.douban.moviedouban.api.model.ActorCollectTable;
import mvp.wyyne.douban.moviedouban.api.model.SearchModelTable;

import mvp.wyyne.douban.moviedouban.model.ActorCollectTableDao;
import mvp.wyyne.douban.moviedouban.model.SearchModelTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig actorCollectTableDaoConfig;
    private final DaoConfig searchModelTableDaoConfig;

    private final ActorCollectTableDao actorCollectTableDao;
    private final SearchModelTableDao searchModelTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        actorCollectTableDaoConfig = daoConfigMap.get(ActorCollectTableDao.class).clone();
        actorCollectTableDaoConfig.initIdentityScope(type);

        searchModelTableDaoConfig = daoConfigMap.get(SearchModelTableDao.class).clone();
        searchModelTableDaoConfig.initIdentityScope(type);

        actorCollectTableDao = new ActorCollectTableDao(actorCollectTableDaoConfig, this);
        searchModelTableDao = new SearchModelTableDao(searchModelTableDaoConfig, this);

        registerDao(ActorCollectTable.class, actorCollectTableDao);
        registerDao(SearchModelTable.class, searchModelTableDao);
    }
    
    public void clear() {
        actorCollectTableDaoConfig.clearIdentityScope();
        searchModelTableDaoConfig.clearIdentityScope();
    }

    public ActorCollectTableDao getActorCollectTableDao() {
        return actorCollectTableDao;
    }

    public SearchModelTableDao getSearchModelTableDao() {
        return searchModelTableDao;
    }

}
